version: "3.8"
services:
  node:
    working_dir: /app
    image: node:18-alpine
    volumes:
      - ./:/app
    tty: true
    ports:
      - "3000:3000"
      - "4173:4173"
    command: yarn dev
  api:
    image: stoplight/prism:latest
    container_name: "api"
    ports:
      - "3001:4010"
    command: mock  -h 0.0.0.0 https://hack-31.github.io/point-app-backend/openapi.yml
